version: 2

models:
  - name: stg_customers
    description: One record per customer
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null
  - name: stg_products
    description: One record per product
    columns:
      - name: product_id
        description: Primary key
        tests:
          - unique
          - not_null
  - name: stg_sales_fact
    description: A table containing multiple forgein keys as well as unit price,cost,discount applied and order quantity
  - name: stg_sales_team
    description: A table containing sales team records
    columns:
      - name: team_id
        description: Primary key
        tests:
          - unique
          - not_null
  - name: stg_store_location
    description: A table containing the various store locations across the United States
    columns:
      - name: Store_id
        description: Primary key
        tests:
          - unique
          - not_null