version: 2

models:
  - name: Total_Revenue
    description: "Calculates the total revenue by multiplying unit price by order quantity and adjusting for discounts"
    columns:
      - name: Total_Revenue
        description: "Total revenue after applying discounts"
    data_tests:
      - unique
      - not_null

  - name: Total_Profit
    description: "Calculates the total profit by subtracting the unit price from the unit cost, multiplying the order quantity and adjusting for discounts"
    columns:
      - name: Total_Profit
        description: "Total profit after applying discounts"
    data_tests:
      - unique
      - not_null
      
  - name: Revenue_per_State
    description: "Calculates the total revenue by multiplying unit price by order quantity and adjusting for discounts"
    columns:
      - name: Revenue_per_State
        description: "Total revenue generated for each state"
    data_tests:
      - unique
      - not_null
      
  - name: Profit_per_Customer
    description: "Calculates the total profit generated from each customers by subtracting the unit price from the unit cost, multiplying the order quantity and adjusting for discounts"
    columns:
      - name: Profit_per_Customer
        description: "Total profit after applying discounts"
    data_tests:
      - unique
      - not_null 

  - name: Total_Product_Revenue
    description: "Calculates the total revenue for each product by multiplying unit price by order quantity and adjusting for discounts"
    columns:
      - name: Total_Product_Revenue
        description: "Total revenue after applying discounts"
    data_tests:
      - unique
      - not_null   

  - name: Total_Sales_Channel_Revenue
    description: "Calculates the total revenue for each sales channel by multiplying unit price by order quantity and adjusting for discounts"
    columns:
      - name: Total_Sales_Channel_Revenue
        description: "Total revenue after applying discounts"
    data_tests:
      - unique
      - not_null


  - name: = Total_Orders_Per_Sales_Channels
    description: "Calculates the total number of orders placed for each sales channel"
    columns:
      - name: Total_Orders_Per_Sales_Channels
        description: "Total orders placed for the various channels"
    data_tests:
      - unique
      - not_null 
  - name: Average_delivery_days
    description: "Calculates the average days for an order to be delivered"
    columns:
      - name: Average_delivery_days
        description: "Average days an order is delivered"
    data_tests:
      - unique
      - not_null 

  - name: Average_shipping_days
    description: "Calculates the average days for an order to be shipped"
    columns:
      - name: Average_shipping_days
        description: "Average days an order is delivered"
    data_tests:
      - unique
      - not_null